// Map dial code to ISO 3166-1 alpha-2 for flag emoji
const CODE_TO_ISO2: Record<string, string> = {
  '+1': 'US', '+44': 'GB', '+91': 'IN', '+86': 'CN', '+81': 'JP', '+49': 'DE',
  '+33': 'FR', '+39': 'IT', '+34': 'ES', '+61': 'AU', '+55': 'BR', '+52': 'MX',
  '+7': 'RU', '+82': 'KR', '+31': 'NL', '+41': 'CH', '+46': 'SE', '+47': 'NO',
  '+45': 'DK', '+358': 'FI', '+48': 'PL', '+90': 'TR', '+971': 'AE', '+972': 'IL',
  '+27': 'ZA', '+234': 'NG', '+20': 'EG', '+60': 'MY', '+65': 'SG', '+66': 'TH',
  '+63': 'PH', '+62': 'ID', '+380': 'UA', '+353': 'IE', '+64': 'NZ', '+351': 'PT',
  '+30': 'GR', '+43': 'AT', '+32': 'BE', '+357': 'CY', '+36': 'HU', '+40': 'RO',
  '+420': 'CZ', '+421': 'SK', '+385': 'HR', '+386': 'SI', '+370': 'LT', '+371': 'LV',
  '+372': 'EE', '+994': 'AZ', '+374': 'AM', '+995': 'GE', '+98': 'IR', '+966': 'SA',
  '+961': 'LB', '+962': 'JO', '+963': 'SY', '+964': 'IQ', '+968': 'OM', '+973': 'BH',
  '+974': 'QA', '+965': 'KW', '+212': 'MA', '+213': 'DZ', '+216': 'TN', '+254': 'KE',
  '+255': 'TZ', '+256': 'UG', '+233': 'GH', '+237': 'CM', '+251': 'ET', '+260': 'ZM',
  '+263': 'ZW', '+84': 'VN', '+92': 'PK', '+880': 'BD', '+94': 'LK', '+977': 'NP',
};

/** Returns flag emoji for a dial code (e.g. "+972" → "🇮🇱") */
export function getFlagEmoji(dialCode: string): string {
  const iso2 = CODE_TO_ISO2[dialCode];
  if (!iso2) return '';
  return [...iso2].map((c) => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0))).join('');
}

// Common country codes for phone number selector
export const COUNTRY_CODES = [
  { code: '+1', country: 'US/Canada' },
  { code: '+44', country: 'UK' },
  { code: '+91', country: 'India' },
  { code: '+86', country: 'China' },
  { code: '+81', country: 'Japan' },
  { code: '+49', country: 'Germany' },
  { code: '+33', country: 'France' },
  { code: '+39', country: 'Italy' },
  { code: '+34', country: 'Spain' },
  { code: '+61', country: 'Australia' },
  { code: '+55', country: 'Brazil' },
  { code: '+52', country: 'Mexico' },
  { code: '+7', country: 'Russia' },
  { code: '+82', country: 'South Korea' },
  { code: '+31', country: 'Netherlands' },
  { code: '+41', country: 'Switzerland' },
  { code: '+46', country: 'Sweden' },
  { code: '+47', country: 'Norway' },
  { code: '+45', country: 'Denmark' },
  { code: '+358', country: 'Finland' },
  { code: '+48', country: 'Poland' },
  { code: '+90', country: 'Turkey' },
  { code: '+971', country: 'UAE' },
  { code: '+972', country: 'Israel' },
  { code: '+27', country: 'South Africa' },
  { code: '+234', country: 'Nigeria' },
  { code: '+20', country: 'Egypt' },
  { code: '+60', country: 'Malaysia' },
  { code: '+65', country: 'Singapore' },
  { code: '+66', country: 'Thailand' },
  { code: '+63', country: 'Philippines' },
  { code: '+62', country: 'Indonesia' },
  { code: '+380', country: 'Ukraine' },
  { code: '+353', country: 'Ireland' },
  { code: '+64', country: 'New Zealand' },
  { code: '+351', country: 'Portugal' },
  { code: '+30', country: 'Greece' },
  { code: '+43', country: 'Austria' },
  { code: '+32', country: 'Belgium' },
  { code: '+357', country: 'Cyprus' },
  { code: '+36', country: 'Hungary' },
  { code: '+40', country: 'Romania' },
  { code: '+420', country: 'Czech Republic' },
  { code: '+421', country: 'Slovakia' },
  { code: '+385', country: 'Croatia' },
  { code: '+386', country: 'Slovenia' },
  { code: '+370', country: 'Lithuania' },
  { code: '+371', country: 'Latvia' },
  { code: '+372', country: 'Estonia' },
  { code: '+994', country: 'Azerbaijan' },
  { code: '+374', country: 'Armenia' },
  { code: '+995', country: 'Georgia' },
  { code: '+98', country: 'Iran' },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+961', country: 'Lebanon' },
  { code: '+962', country: 'Jordan' },
  { code: '+963', country: 'Syria' },
  { code: '+964', country: 'Iraq' },
  { code: '+968', country: 'Oman' },
  { code: '+973', country: 'Bahrain' },
  { code: '+974', country: 'Qatar' },
  { code: '+965', country: 'Kuwait' },
  { code: '+212', country: 'Morocco' },
  { code: '+213', country: 'Algeria' },
  { code: '+216', country: 'Tunisia' },
  { code: '+254', country: 'Kenya' },
  { code: '+255', country: 'Tanzania' },
  { code: '+256', country: 'Uganda' },
  { code: '+233', country: 'Ghana' },
  { code: '+237', country: 'Cameroon' },
  { code: '+251', country: 'Ethiopia' },
  { code: '+260', country: 'Zambia' },
  { code: '+263', country: 'Zimbabwe' },
  { code: '+84', country: 'Vietnam' },
  { code: '+92', country: 'Pakistan' },
  { code: '+880', country: 'Bangladesh' },
  { code: '+94', country: 'Sri Lanka' },
  { code: '+977', country: 'Nepal' },
];
