export const SECURITY_QUESTIONS = [
  'Do you have a communicable disease of public health significance such as tuberculosis (TB)?',
  'Do you have documentation to establish that you have received vaccinations in accordance with U.S. law?',
  'Do you have a mental or physical disorder that poses or is likely to pose a threat to the safety or welfare of yourself or others?',
  'Are you or have you ever been a drug abuser or addict?',
  'Have you ever been arrested or convicted for any offense or crime, even though subject of a pardon, amnesty, or other similar action?',
  'Have you ever violated, or engaged in a conspiracy to violate, any law relating to controlled substances?',
  'Are you the spouse, son, or daughter of an individual who has violated any controlled substance trafficking law, and have knowingly benefited from the trafficking activities in the past five years?',
  'Are you coming to the United States to engage in prostitution or unlawful commercialized vice or have you been engaged in prostitution or procuring prostitutes within the past 10 years?',
  'Have you ever been involved in, or do you seek to engage in, money laundering?',
  'Have you ever committed or conspired to commit a human trafficking offense in the United States or outside the United States?',
  'Have you ever knowingly aided, abetted, assisted, or colluded with an individual who has been identified by the President of the United States as a person who plays a significant role in a severe form of trafficking in persons?',
  'Are you the spouse, son, or daughter of an individual who has committed or conspired to commit a human trafficking offense in the United States or outside the United States and have you within the last five years, knowingly benefited from the trafficking activities?',
  'Do you seek to engage in espionage, sabotage, export control violations, or any other illegal activity while in the United States?',
  'Do you seek to engage in terrorist activities while in the United States or have you ever engaged in terrorist activities?',
  'Have you ever or do you intend to provide financial assistance or other support to terrorists or terrorist organizations?',
  'Are you a member or representative of a terrorist organization?',
  'Are you the spouse, son, or daughter of an individual who has engaged in terrorist activity, including providing financial assistance or other support to terrorists or terrorist organizations, in the last five years?',
  'Have you ever ordered, incited, committed, assisted, or otherwise participated in genocide?',
  'Have you ever committed, ordered, incited, assisted, or otherwise participated in torture?',
  'Have you committed, ordered, incited, assisted, or otherwise participated in extrajudicial killings, political killings, or other acts of violence?',
  'Have you ever engaged in the recruitment of or the use of child soldiers?',
  'Have you, while serving as a government official, been responsible for or directly carried out, at any time, particularly severe violations of religious freedom?',
  'Are you a member of or affiliated with the Communist or other totalitarian party?',
  'Have you ever directly or indirectly assisted or supported any of the groups in Columbia known as the Revolutionary Armed Forces of Columbia (FARC), National Liberation Army (ELN), or United Self-Defense Forces of Columbia (AUC)?',
  'Have you ever, through abuse of governmental or political position converted for personal gain, confiscated or expropriated property in a foreign nation to which a United States national had claim of ownership?',
  'Are you the spouse, minor child, or agent of an individual who has through abuse of governmental or political position converted for personal gain, confiscated or expropriated property in a foreign nation to which a United States national had claim of ownership?',
  'Have you ever been directly involved in the establishment or enforcement of population controls forcing a woman to undergo an abortion against her free choice or a man or a woman to undergo sterilization against his or her free choice?',
  'Have you ever disclosed or trafficked in confidential U.S. business information obtained in connection with U.S. participation in the Chemical Weapons Convention?',
  'Are you the spouse, minor child, or agent of an individual who has disclosed or trafficked in confidential U.S. business information obtained in connection with U.S. participation in the Chemical Weapons Convention?',
  'Have you ever sought to obtain or assist others to obtain a visa, entry into the United States, or any other United States immigration benefit by fraud or willful misrepresentation or other unlawful means?',
  'Have you ever been removed or deported from any country?',
  'Have you ever been the subject of a removal or deportation hearing?',
  'Have you failed to attend a hearing on removability or inadmissibility within the last five years?',
  'Have you ever been unlawfully present, overstayed the amount of time granted by an immigration official or otherwise violated the terms of a U.S. visa?',
  'Are you subject to a civil penalty under INA 274C?',
  'Have you been ordered removed from the U.S. during the last five years?',
  'Have you been ordered removed from the U.S. for a second time within the last 20 years?',
  'Have you ever been unlawfully present and ordered removed from the U.S. during the last ten years?',
  'Have you ever been convicted of an aggravated felony and been ordered removed from the U.S.?',
  'Have you ever been unlawfully present in the U.S. for more than 180 days (but no more than one year) and have voluntarily departed the U.S. within the last three years?',
  'Have you ever been unlawfully present in the U.S. for more than one year or more than one year in the aggregate at any time during the last 10 years?',
  'Have you ever withheld custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?',
  'Have you ever intentionally assisted another person in withholding custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?',
  'Have you voted in the United States in violation of any law or regulation?',
  'Have you ever renounced United States citizenship for the purpose of avoiding taxation?',
  'Have you attended a public elementary school or a public secondary school on student (F) status after November 30, 1996 without reimbursing the school?',
  'Do you seek to enter the United States for the purpose of performing skilled or unskilled labor but have not yet been certified by the Secretary of Labor?',
  'Are you a graduate of a foreign medical school seeking to perform medical services in the United States but have not yet passed the National Board of Medical Examiners examination or its equivalent?',
  'Are you a health care worker seeking to perform such work in the United States but have not yet received certification from the Commission on Graduates of Foreign Nursing Schools or from an equivalent approved independent credentialing organization?',
  'Are you permanently ineligible for U.S. citizenship?',
  'Have you ever departed the United States in order to evade military service during a time of war?',
  'Are you coming to the U.S. to practice polygamy?',
  'Are you a former exchange visitor (J) who has not yet fulfilled the two-year foreign residence requirement?',
  'Has the Secretary of Homeland Security of the United States ever determined that you knowingly made a frivolous application for asylum?',
  'Are you likely to become a public charge after you are admitted to the United States?',
];
